name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1' # Version LTS compatible

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Build l’application
      - name: Build
        run: npm run build

      # Déployer vers Netlify (à activer plus tard)
      # - name: Deploy to Netlify
      #   run: npx netlify-cli deploy --prod --dir=dist
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}