name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ajout : changer de répertoire
      - name: Change to project directory
        run: cd SalemWorld

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Déploiement Netlify (commenté pour l’instant)
      # - name: Deploy to Netlify
      #   run: npx netlify-cli deploy --prod --dir=dist
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}