name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ajout : changer de répertoire
      - name: Change to project directory
        run: cd SalemWorld

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug directory
        run: ls -l
  
      - name: Install dependencies
        run: |
            cd SalemWorld
              npm install

      - name: Build
        run: |
          cd SalemWorld
          npm run build


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        run: aws s3 sync index.html s3://${{ secrets.AWS_S3_BUCKET }} --delete
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./SalemWorld
          file: ./SalemWorld/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/salemworld:latest


