name: CI/CD Pipeline Vue.js
on:
  push:
    branches:
      - CI/CD
      - main
  pull_request:
    branches:
      - CI/CD
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to Server
        if: success()
        run: |
          echo "Deploying to production server..."
          # Add your deployment command here